# Getting familiar with the coco library in python 

The goal of this cell is to get knowledge on how the data looks like. Here i am picking a specific data: the dim 2 and the first function.

I also want to see how it presents the data, here we have: 
- Targets (precision reached)
- Fevals (nbr of evaluations before reaching a acertain preciison) 
- Instances (this is the numer of times we repeat the experiment for a given function and a given algo and a goven dimension, we are simply imputing differnt starting values for the function)  

Tragets: the grid of target precisions (Δf = f(x) − f*), from 1e2 down to 1e-8.
One value per row of the table.

In [1]:
import cocopp
dsl = cocopp.load("bbob/2009/*")

In [2]:
dd = dsl.dictByDimFunc()

ds_list = dd[2][1]        # list of DataSet for dim=2, f1
ds0 = ds_list[0]          # pick ONE dataset (one algo)

# Option A — use the precomputed table (targets × runs)
targets  = ds0.evals[:, 0]
fevals   = ds0.evals[:, 1:]      # (#targets, #instances)
instances = ds0.instancenumbers  # usually length 15
targets


array([1.00000000e+02, 6.30957344e+01, 3.98107171e+01, 2.51188643e+01,
       1.58489319e+01, 1.00000000e+01, 6.30957344e+00, 3.98107171e+00,
       2.51188643e+00, 1.58489319e+00, 1.00000000e+00, 6.30957344e-01,
       3.98107171e-01, 2.51188643e-01, 1.58489319e-01, 1.00000000e-01,
       6.30957344e-02, 3.98107171e-02, 2.51188643e-02, 1.58489319e-02,
       1.00000000e-02, 6.30957344e-03, 3.98107171e-03, 2.51188643e-03,
       1.58489319e-03, 1.00000000e-03, 6.30957344e-04, 3.98107171e-04,
       2.51188643e-04, 1.58489319e-04, 1.00000000e-04, 6.30957344e-05,
       3.98107171e-05, 2.51188643e-05, 1.58489319e-05, 1.00000000e-05,
       6.30957344e-06, 3.98107171e-06, 2.51188643e-06, 1.58489319e-06,
       1.00000000e-06, 6.30957344e-07, 3.98107171e-07, 2.51188643e-07,
       1.58489319e-07, 1.00000000e-07, 6.30957344e-08, 3.98107171e-08,
       2.51188643e-08, 1.58489319e-08, 1.00000000e-08])

Fevals: (shape = n_targets × 15) = for each target (row) and each instance (column), the number of function evaluations needed to first hit that target.
1s at the top rows are normal: coarse targets like 1e2 are often already met at the first evaluation.
Unreached targets would be np.inf

In [4]:
fevals

array([[1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00,
        1.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00,
        1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 3.000e+00,
        2.000e+00, 1.000e+00, 1.000e+00],
       [1.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 2.000e+00, 1.000e+00,
        1.000e+00, 2.000e+00, 1.000e+00, 1.000e+00, 1.000e+00, 4.000e+00,
        2.000e+00, 2.000e+00, 1.000e+00],
       [2.000e+00, 1.000e+00, 3.000e+00, 1.000e+00, 2.000e+00, 1.000e+00,
        2.000e+00, 8.000e+00, 1.000e+00, 4.000e+00, 3.000e+00, 1.100e+01,
        4.000e+00, 4.000e+00, 1.000e+00],
       [2.000e+00, 6.000e+00, 4.000e+00, 1.000e+00

We also wnat to get familiar wit the ERT, this is an important indicator. We want the lowest ERT this means the best performance for an algo. Bcause that means .... TO BE COMPLETED

In [7]:
# pick one dataset (dim=2, F1, first algo)

ds0.target[:5], ds0.ert[:5]     # targets and matching ERTs


(array([100.        ,  63.09573445,  39.81071706,  25.11886432,
         15.84893192]),
 array([1.        , 1.06666667, 1.33333333, 1.46666667, 3.2       ]))

We can also summarize the data into a table, this is a bbuilt function inside the coco library. 

In [6]:
ds0.info()

Algorithm: ALPS_hornby
Function ID: 1
Dimension DIM = 2
Number of trials: 15
Final target Df: 1e-08
min / max number of evals per trial: 5858 / 7977
   evals/DIM:  best     15%     50%     85%     max |  ERT/DIM  nsucc
  ---Df---|-----------------------------------------|----------------
  1.0e+03 |       0       0       0       0       0 |      0.5  15
  1.0e+01 |       0       1       2       4       8 |      2.5  15
  1.0e-01 |      22      43     142     276     374 |    158.3  15
  1.0e-03 |     404     540     902    1136    1319 |    868.0  15
  1.0e-05 |    1176    1686    1966    2142    2286 |   1906.1  15
  1.0e-08 |    2929    3149    3452    3635    3988 |   3450.5  15
